import type { LocaleCode } from "@/data/locales";

type LegalSection = {
  title: string;
  body: string[];
  bullets?: string[];
};

type LegalPageContent = {
  title: string;
  description: string;
  intro: string;
  sections: LegalSection[];
};

type ContactContent = {
  title: string;
  description: string;
  intro: string;
  emailLabel: string;
  emailValue: string;
  emailHelp: string;
  replaceTitle: string;
  replaceBody: string;
  responseTitle: string;
  responseBody: string;
};

type FooterLinkLabels = {
  privacy: string;
  terms: string;
  about: string;
  contact: string;
};

export type LegalPageKey = "privacy" | "terms" | "about";

type TrustMessages = {
  footerLinks: FooterLinkLabels;
  legal: Record<LegalPageKey, LegalPageContent>;
  contact: ContactContent;
};

export const trustMessages: Record<LocaleCode, TrustMessages> = {
  en: {
    footerLinks: {
      privacy: "Privacy Policy",
      terms: "Terms of Use",
      about: "About",
      contact: "Contact"
    },
    legal: {
      privacy: {
        title: "Privacy Policy",
        description: "Learn the basic privacy practices for this multilingual browser-based tools website.",
        intro:
          "This website is a small independent tools hub. We aim to keep data handling simple, limited, and easy to understand.",
        sections: [
          {
            title: "Information you enter into tools",
            body: [
              "Some tools let you paste text, URLs, image data, or other content so the tool can generate a result in your browser.",
              "Please avoid submitting private, sensitive, or confidential material unless you are comfortable with that data being processed for the requested tool action."
            ]
          },
          {
            title: "Website fetching and previews",
            body: [
              "Some tools may request public webpage metadata, preview images, thumbnails, or other publicly available assets in order to show a result.",
              "These requests are intended to support the tool feature you selected and should only be used for pages and content you have the right to analyze or reference."
            ]
          },
          {
            title: "Usage data",
            body: [
              "Basic technical information such as browser type, device information, or approximate usage logs may be collected to keep the site working, prevent abuse, and improve reliability.",
              "Analytics, advertising, or similar services may be added in the future to understand site usage or support the project. If that happens, this page should be updated to reflect the change."
            ]
          },
          {
            title: "Third-party services",
            body: [
              "This site may rely on hosting, infrastructure, or embedded third-party services that process limited technical data as part of delivering the website.",
              "Each third-party service may have its own privacy terms and practices."
            ]
          },
          {
            title: "Your choices",
            body: [
              "If you do not want certain information processed, do not submit it through the tools.",
              "If you add a real support email later, you can also use that channel for basic privacy-related questions."
            ]
          }
        ]
      },
      terms: {
        title: "Terms of Use",
        description: "Read the basic terms for using this small independent online tools website.",
        intro:
          "By using this website, you agree to use the tools responsibly and only for lawful purposes.",
        sections: [
          {
            title: "Acceptable use",
            body: ["You may use the site for normal personal, educational, or business workflow tasks."],
            bullets: [
              "Do not misuse the site, overload it, or attempt to interfere with normal operation.",
              "Do not use the tools for unlawful, harmful, infringing, or abusive activity.",
              "Only submit content or URLs that you have the right to use, inspect, or process."
            ]
          },
          {
            title: "Your responsibility",
            body: [
              "You are responsible for the data you enter, the URLs you analyze, and how you use the output generated by the tools.",
              "Please review results before relying on them for publishing, compliance, marketing, or technical decisions."
            ]
          },
          {
            title: "As-is service",
            body: [
              "The tools are provided on an as-is and as-available basis.",
              "Features may change, be updated, become unavailable, or produce incomplete results without notice."
            ]
          },
          {
            title: "No warranty and limited liability",
            body: [
              "To the extent allowed by law, this site makes no warranty regarding accuracy, availability, or fitness for a particular purpose.",
              "The site operator is not responsible for losses or damages arising from your use of the tools or reliance on tool output."
            ]
          }
        ]
      },
      about: {
        title: "About",
        description: "Learn what this multilingual tools site is for and who it is designed to help.",
        intro:
          "This website is a practical multilingual hub for browser-based utility tools that are easy to access and simple to use.",
        sections: [
          {
            title: "What this site offers",
            body: [
              "The focus is on straightforward tools for creators, marketers, and developers who want quick results without installing extra software.",
              "Examples include image helpers, preview tools, formatting utilities, link tools, and small workflow boosters for everyday web tasks."
            ]
          },
          {
            title: "Multilingual by design",
            body: [
              "The site is built to support multiple locales so visitors can browse tools and basic site information in a language that feels more comfortable.",
              "The goal is to keep the experience clear, lightweight, and consistent across languages."
            ]
          },
          {
            title: "Simple and trustworthy",
            body: [
              "This is intended to be a clean independent tools website with practical pages, understandable copy, and accessible navigation.",
              "The project will continue improving step by step with a focus on useful features and a beginner-friendly experience."
            ]
          }
        ]
      }
    },
    contact: {
      title: "Contact",
      description: "Find the current contact placeholder for this tools website and replace it with your real support details later.",
      intro:
        "If you want to hear from users, keep the contact method simple and easy to maintain. You can replace the placeholder details below before launch.",
      emailLabel: "Contact email",
      emailValue: "hello@example.com",
      emailHelp: "Placeholder only — replace this with your real support email before launch.",
      replaceTitle: "Easy to update later",
      replaceBody:
        "This page is intentionally simple so a beginner can quickly swap in a real email address, support form link, or social contact method without changing the whole layout.",
      responseTitle: "What users can contact you about",
      responseBody:
        "Typical topics include broken tools, translation issues, feedback, partnership questions, or general support requests."
    }
  },
  ko: {
    footerLinks: {
      privacy: "개인정보 처리방침",
      terms: "이용약관",
      about: "소개",
      contact: "문의"
    },
    legal: {
      privacy: {
        title: "개인정보 처리방침",
        description: "이 다국어 브라우저 기반 도구 사이트의 기본적인 개인정보 처리 방침을 안내합니다.",
        intro:
          "이 웹사이트는 소규모 독립형 도구 허브입니다. 데이터 처리는 단순하고 제한적이며 이해하기 쉽게 유지하는 것을 목표로 합니다.",
        sections: [
          {
            title: "도구에 입력하는 정보",
            body: [
              "일부 도구는 결과를 생성하기 위해 텍스트, URL, 이미지 데이터 또는 기타 콘텐츠를 브라우저에서 입력받을 수 있습니다.",
              "민감하거나 비공개인 자료는 해당 도구 처리에 사용되어도 괜찮은 경우에만 제출해 주세요."
            ]
          },
          {
            title: "웹페이지 조회 및 미리보기",
            body: [
              "일부 도구는 결과를 보여주기 위해 공개 웹페이지의 메타데이터, 미리보기 이미지, 썸네일 또는 공개 자산을 가져올 수 있습니다.",
              "이러한 요청은 선택한 도구 기능을 위한 것이며, 분석하거나 참조할 권한이 있는 페이지와 콘텐츠에 대해서만 사용해야 합니다."
            ]
          },
          {
            title: "이용 데이터",
            body: [
              "브라우저 종류, 기기 정보, 기본 사용 로그와 같은 기술 정보는 사이트 운영, 오남용 방지, 안정성 개선을 위해 수집될 수 있습니다.",
              "향후 사이트 이용 현황 파악이나 프로젝트 운영 지원을 위해 분석 도구나 광고 서비스가 추가될 수 있습니다. 그런 변경이 생기면 이 페이지도 함께 업데이트되어야 합니다."
            ]
          },
          {
            title: "제3자 서비스",
            body: [
              "이 사이트는 웹사이트 제공 과정에서 제한적인 기술 데이터를 처리하는 호스팅, 인프라 또는 임베드형 제3자 서비스를 사용할 수 있습니다.",
              "각 제3자 서비스에는 자체 개인정보 처리 기준이 있을 수 있습니다."
            ]
          },
          {
            title: "사용자의 선택",
            body: [
              "특정 정보가 처리되는 것을 원하지 않는다면 도구에 해당 정보를 입력하지 마세요.",
              "나중에 실제 지원 이메일을 추가하면 기본적인 개인정보 관련 문의 창구로도 활용할 수 있습니다."
            ]
          }
        ]
      },
      terms: {
        title: "이용약관",
        description: "이 소규모 독립형 온라인 도구 사이트의 기본 이용 조건을 안내합니다.",
        intro: "이 웹사이트를 사용하면 도구를 책임감 있게, 그리고 합법적인 목적에 한해 사용한다는 데 동의하는 것으로 봅니다.",
        sections: [
          {
            title: "허용되는 사용",
            body: ["개인, 교육, 업무용 일반 작업 흐름에서 사이트를 사용할 수 있습니다."],
            bullets: [
              "사이트를 오용하거나 과도한 부하를 주거나 정상적인 운영을 방해하려고 해서는 안 됩니다.",
              "도구를 불법적이거나 유해하거나 권리를 침해하거나 남용적인 활동에 사용해서는 안 됩니다.",
              "사용, 확인 또는 처리할 권한이 있는 콘텐츠와 URL만 제출하세요."
            ]
          },
          {
            title: "사용자 책임",
            body: [
              "입력한 데이터, 분석한 URL, 그리고 도구 결과물을 사용하는 방식에 대한 책임은 사용자에게 있습니다.",
              "게시, 규정 준수, 마케팅 또는 기술적 판단에 활용하기 전에 결과를 직접 확인해 주세요."
            ]
          },
          {
            title: "현상 그대로 제공",
            body: [
              "도구는 현재 제공 가능한 상태 그대로 제공됩니다.",
              "기능은 예고 없이 변경, 업데이트, 중단되거나 불완전한 결과를 낼 수 있습니다."
            ]
          },
          {
            title: "보증 부인 및 책임 제한",
            body: [
              "법이 허용하는 범위 내에서 이 사이트는 정확성, 가용성, 특정 목적 적합성에 대해 보증하지 않습니다.",
              "도구 사용 또는 결과물 의존으로 인해 발생한 손실이나 손해에 대해 사이트 운영자는 책임을 지지 않습니다."
            ]
          }
        ]
      },
      about: {
        title: "소개",
        description: "이 다국어 도구 사이트의 목적과 누구를 위한 서비스인지 소개합니다.",
        intro: "이 웹사이트는 쉽게 접근하고 간단하게 사용할 수 있는 브라우저 기반 유틸리티 도구를 모아 둔 실용적인 다국어 허브입니다.",
        sections: [
          {
            title: "사이트에서 제공하는 것",
            body: [
              "추가 소프트웨어 설치 없이 빠르게 결과를 얻고 싶은 크리에이터, 마케터, 개발자를 위한 직관적인 도구에 초점을 맞추고 있습니다.",
              "예를 들어 이미지 보조 도구, 미리보기 도구, 포맷팅 유틸리티, 링크 도구, 일상적인 웹 작업을 돕는 작은 기능들이 포함됩니다."
            ]
          },
          {
            title: "다국어 중심 설계",
            body: [
              "방문자가 더 편한 언어로 도구와 기본 사이트 정보를 볼 수 있도록 여러 로케일을 지원하도록 구축되었습니다.",
              "목표는 언어가 달라도 명확하고 가볍고 일관된 경험을 제공하는 것입니다."
            ]
          },
          {
            title: "단순하고 신뢰할 수 있게",
            body: [
              "이 사이트는 실용적인 페이지, 이해하기 쉬운 문구, 접근성 좋은 탐색 구조를 갖춘 깔끔한 독립형 도구 사이트를 지향합니다.",
              "프로젝트는 유용한 기능과 초보자도 관리하기 쉬운 경험에 집중하며 단계적으로 개선될 예정입니다."
            ]
          }
        ]
      }
    },
    contact: {
      title: "문의",
      description: "현재 이 도구 사이트에 설정된 연락처 자리표시자를 확인하고 나중에 실제 지원 정보로 교체하세요.",
      intro: "사용자 의견을 받고 싶다면 연락 수단은 단순하고 관리하기 쉬운 방식이 좋습니다. 아래 자리표시자는 출시 전에 실제 정보로 교체하세요.",
      emailLabel: "연락 이메일",
      emailValue: "hello@example.com",
      emailHelp: "자리표시자 전용입니다. 출시 전에 실제 지원 이메일로 바꿔 주세요.",
      replaceTitle: "나중에 쉽게 수정 가능",
      replaceBody:
        "이 페이지는 초보자도 전체 레이아웃을 바꾸지 않고 실제 이메일, 지원 폼 링크, 소셜 연락 채널로 빠르게 교체할 수 있도록 단순하게 구성했습니다.",
      responseTitle: "사용자가 문의할 수 있는 내용",
      responseBody: "예를 들면 도구 오류, 번역 문제, 피드백, 협업 문의, 일반 지원 요청 등이 있습니다."
    }
  },
  ja: {
    footerLinks: {
      privacy: "プライバシーポリシー",
      terms: "利用規約",
      about: "このサイトについて",
      contact: "お問い合わせ"
    },
    legal: {
      privacy: {
        title: "プライバシーポリシー",
        description: "この多言語ブラウザベースのツールサイトにおける基本的なプライバシー方針を案内します。",
        intro:
          "このWebサイトは小規模な独立系ツールハブです。データの取り扱いは、できるだけシンプルで限定的かつ分かりやすい形を目指しています。",
        sections: [
          {
            title: "ツールに入力する情報",
            body: [
              "一部のツールでは、結果を生成するためにテキスト、URL、画像データ、その他の内容をブラウザ上で入力できます。",
              "非公開情報や機密性の高い情報は、そのツール処理に使われても問題ない場合にのみ送信してください。"
            ]
          },
          {
            title: "Webページの取得とプレビュー",
            body: [
              "一部のツールでは、結果表示のために公開Webページのメタデータ、プレビュー画像、サムネイル、その他の公開アセットを取得する場合があります。",
              "これらの取得は選択した機能を提供する目的で行われ、分析または参照する権利があるページやコンテンツにのみ利用してください。"
            ]
          },
          {
            title: "利用データ",
            body: [
              "ブラウザ種別、端末情報、基本的な利用ログなどの技術情報は、サイト運営、不正利用の防止、安定性向上のために収集されることがあります。",
              "将来的に、利用状況の把握やプロジェクト維持のために分析サービスや広告サービスを追加する可能性があります。その場合は、このページも更新されるべきです。"
            ]
          },
          {
            title: "第三者サービス",
            body: [
              "このサイトでは、Webサイト提供のために限定的な技術データを処理するホスティング、インフラ、埋め込み型の第三者サービスを利用する場合があります。",
              "各第三者サービスには独自のプライバシー方針がある場合があります。"
            ]
          },
          {
            title: "利用者の選択",
            body: [
              "特定の情報を処理されたくない場合は、その情報をツールに入力しないでください。",
              "後で実際のサポート用メールアドレスを追加した場合は、基本的なプライバシー関連の問い合わせ窓口としても使えます。"
            ]
          }
        ]
      },
      terms: {
        title: "利用規約",
        description: "この小規模な独立系オンラインツールサイトの基本的な利用条件を案内します。",
        intro: "このWebサイトを利用することで、利用者はツールを責任を持って、かつ適法な目的のためにのみ使用することに同意したものとみなされます。",
        sections: [
          {
            title: "許容される利用",
            body: ["個人利用、学習用途、業務上の通常ワークフローのために本サイトを利用できます。"],
            bullets: [
              "サイトを乱用したり、過度な負荷をかけたり、通常運用を妨害しようとしてはいけません。",
              "違法、有害、権利侵害、または迷惑行為のためにツールを利用してはいけません。",
              "利用、確認、処理する権利のあるコンテンツやURLのみ送信してください。"
            ]
          },
          {
            title: "利用者の責任",
            body: [
              "入力するデータ、分析するURL、そしてツール出力の利用方法については利用者自身が責任を負います。",
              "公開、コンプライアンス、マーケティング、技術判断に使う前に、結果を必ず確認してください。"
            ]
          },
          {
            title: "現状有姿での提供",
            body: [
              "ツールは現状有姿かつ提供可能な範囲で提供されます。",
              "機能は予告なく変更、更新、停止されたり、不完全な結果を返したりする場合があります。"
            ]
          },
          {
            title: "保証否認と責任制限",
            body: [
              "法令で認められる範囲で、このサイトは正確性、可用性、特定目的への適合性について保証しません。",
              "ツールの利用や出力結果への依拠によって生じた損失や損害について、サイト運営者は責任を負いません。"
            ]
          }
        ]
      },
      about: {
        title: "このサイトについて",
        description: "この多言語ツールサイトの目的と、どのような利用者を想定しているかを紹介します。",
        intro: "このWebサイトは、すぐに使えて分かりやすいブラウザベースのユーティリティツールを集めた実用的な多言語ハブです。",
        sections: [
          {
            title: "提供しているもの",
            body: [
              "追加ソフトなしで素早く結果を得たいクリエイター、マーケター、開発者向けのシンプルなツールに注力しています。",
              "画像補助、プレビュー、整形ユーティリティ、リンク作成、日々のWeb作業を助ける小さな機能などが含まれます。"
            ]
          },
          {
            title: "多言語対応を前提に設計",
            body: [
              "訪問者がより使いやすい言語でツールや基本情報を閲覧できるよう、複数ロケールに対応する構成になっています。",
              "言語が変わっても、分かりやすく、軽く、一貫した体験を保つことを目指しています。"
            ]
          },
          {
            title: "シンプルで信頼しやすく",
            body: [
              "このサイトは、実用的なページ、理解しやすい文章、使いやすいナビゲーションを備えたクリーンな独立系ツールサイトを目指しています。",
              "今後も役立つ機能と初心者にも扱いやすい体験を重視しながら、少しずつ改善していきます。"
            ]
          }
        ]
      }
    },
    contact: {
      title: "お問い合わせ",
      description: "このツールサイトの現在の連絡先プレースホルダーを確認し、後から実際のサポート情報に差し替えられるようにしています。",
      intro: "ユーザーからの連絡を受けたい場合は、管理しやすいシンプルな連絡手段がおすすめです。以下のプレースホルダーは公開前に実際の情報へ置き換えてください。",
      emailLabel: "連絡先メール",
      emailValue: "hello@example.com",
      emailHelp: "プレースホルダーです。公開前に実際のサポート用メールアドレスへ変更してください。",
      replaceTitle: "あとで簡単に更新できます",
      replaceBody:
        "このページは、初心者でもレイアウト全体を作り直さずに実際のメールアドレス、問い合わせフォームへのリンク、SNS連絡先などへ差し替えやすいようにシンプルにしてあります。",
      responseTitle: "想定される問い合わせ内容",
      responseBody: "ツールの不具合、翻訳の問題、フィードバック、連携相談、一般的なサポート依頼などを想定しています。"
    }
  },
  es: {
    footerLinks: {
      privacy: "Política de privacidad",
      terms: "Términos de uso",
      about: "Acerca de",
      contact: "Contacto"
    },
    legal: {
      privacy: {
        title: "Política de privacidad",
        description: "Conoce las prácticas básicas de privacidad de este sitio web multilingüe de herramientas en el navegador.",
        intro:
          "Este sitio web es un pequeño centro independiente de herramientas. El objetivo es mantener el tratamiento de datos de forma simple, limitada y fácil de entender.",
        sections: [
          {
            title: "Información que introduces en las herramientas",
            body: [
              "Algunas herramientas permiten pegar texto, URL, datos de imagen u otro contenido para generar un resultado en tu navegador.",
              "Evita enviar material privado, sensible o confidencial salvo que estés de acuerdo con que esos datos se procesen para la acción solicitada."
            ]
          },
          {
            title: "Obtención de páginas y vistas previas",
            body: [
              "Algunas herramientas pueden solicitar metadatos públicos de páginas web, imágenes de vista previa, miniaturas u otros recursos públicos para mostrar un resultado.",
              "Estas solicitudes están pensadas para la función que elegiste y solo deben usarse con páginas o contenido que tengas derecho a analizar o consultar."
            ]
          },
          {
            title: "Datos de uso",
            body: [
              "Información técnica básica como tipo de navegador, datos del dispositivo o registros aproximados de uso puede recopilarse para mantener el sitio, prevenir abusos y mejorar la fiabilidad.",
              "En el futuro podrían añadirse servicios de analítica, publicidad o similares para entender el uso del sitio o apoyar el proyecto. Si eso ocurre, esta página debería actualizarse."
            ]
          },
          {
            title: "Servicios de terceros",
            body: [
              "Este sitio puede depender de servicios de alojamiento, infraestructura o integraciones de terceros que procesen datos técnicos limitados como parte de la entrega del sitio web.",
              "Cada servicio de terceros puede tener sus propias condiciones y prácticas de privacidad."
            ]
          },
          {
            title: "Tus opciones",
            body: [
              "Si no quieres que cierta información se procese, no la envíes a través de las herramientas.",
              "Si más adelante añades un correo real de soporte, también podrás usar ese canal para consultas básicas relacionadas con privacidad."
            ]
          }
        ]
      },
      terms: {
        title: "Términos de uso",
        description: "Lee las condiciones básicas para usar este pequeño sitio independiente de herramientas online.",
        intro: "Al usar este sitio web, aceptas utilizar las herramientas de forma responsable y solo con fines legales.",
        sections: [
          {
            title: "Uso aceptable",
            body: ["Puedes usar el sitio para tareas normales de trabajo personal, educativo o profesional."],
            bullets: [
              "No uses el sitio de forma abusiva, no lo sobrecargues ni intentes interferir con su funcionamiento normal.",
              "No utilices las herramientas para actividades ilegales, dañinas, infractoras o abusivas.",
              "Envía únicamente contenido o URL que tengas derecho a usar, revisar o procesar."
            ]
          },
          {
            title: "Tu responsabilidad",
            body: [
              "Eres responsable de los datos que introduces, de las URL que analizas y del uso que haces del resultado generado por las herramientas.",
              "Revisa los resultados antes de basarte en ellos para decisiones de publicación, cumplimiento, marketing o técnicas."
            ]
          },
          {
            title: "Servicio tal cual",
            body: [
              "Las herramientas se ofrecen tal cual y según disponibilidad.",
              "Las funciones pueden cambiar, actualizarse, dejar de estar disponibles o producir resultados incompletos sin previo aviso."
            ]
          },
          {
            title: "Sin garantía y responsabilidad limitada",
            body: [
              "En la medida permitida por la ley, este sitio no ofrece garantías sobre precisión, disponibilidad o idoneidad para un propósito concreto.",
              "El operador del sitio no es responsable de pérdidas o daños derivados del uso de las herramientas o de la confianza depositada en sus resultados."
            ]
          }
        ]
      },
      about: {
        title: "Acerca de",
        description: "Descubre para qué sirve este sitio multilingüe de herramientas y a quién está dirigido.",
        intro:
          "Este sitio web es un centro práctico y multilingüe de utilidades basadas en el navegador, pensado para ser fácil de usar y accesible.",
        sections: [
          {
            title: "Qué ofrece el sitio",
            body: [
              "Se centra en herramientas sencillas para creadores, especialistas en marketing y desarrolladores que quieren resultados rápidos sin instalar software adicional.",
              "Incluye ayudas para imágenes, herramientas de vista previa, utilidades de formato, herramientas de enlaces y pequeños apoyos para tareas web del día a día."
            ]
          },
          {
            title: "Diseño multilingüe",
            body: [
              "El sitio está preparado para admitir varios idiomas para que los visitantes puedan consultar las herramientas y la información básica en un idioma más cómodo.",
              "La meta es mantener una experiencia clara, ligera y coherente en todos los idiomas."
            ]
          },
          {
            title: "Simple y confiable",
            body: [
              "La intención es ofrecer un sitio independiente de herramientas con páginas prácticas, textos comprensibles y navegación accesible.",
              "El proyecto seguirá mejorando paso a paso, con foco en funciones útiles y una experiencia fácil de mantener para principiantes."
            ]
          }
        ]
      }
    },
    contact: {
      title: "Contacto",
      description: "Consulta el marcador de contacto actual de este sitio de herramientas y sustitúyelo más adelante por tus datos reales de soporte.",
      intro:
        "Si quieres recibir mensajes de los usuarios, conviene mantener el método de contacto simple y fácil de gestionar. Puedes reemplazar los datos de ejemplo antes del lanzamiento.",
      emailLabel: "Correo de contacto",
      emailValue: "hello@example.com",
      emailHelp: "Solo es un marcador de posición: sustitúyelo por tu correo real de soporte antes del lanzamiento.",
      replaceTitle: "Fácil de actualizar después",
      replaceBody:
        "Esta página es intencionalmente simple para que una persona principiante pueda cambiar rápido a un correo real, un enlace a formulario de soporte o un método de contacto social sin rehacer el diseño completo.",
      responseTitle: "Temas sobre los que pueden escribirte",
      responseBody:
        "Los temas típicos incluyen herramientas rotas, problemas de traducción, comentarios, preguntas de colaboración o solicitudes generales de soporte."
    }
  },
  fr: {
    footerLinks: {
      privacy: "Politique de confidentialité",
      terms: "Conditions d'utilisation",
      about: "À propos",
      contact: "Contact"
    },
    legal: {
      privacy: {
        title: "Politique de confidentialité",
        description: "Découvrez les pratiques de base en matière de confidentialité de ce site d'outils multilingue dans le navigateur.",
        intro:
          "Ce site est un petit hub indépendant d'outils. L'objectif est de garder le traitement des données simple, limité et facile à comprendre.",
        sections: [
          {
            title: "Informations saisies dans les outils",
            body: [
              "Certains outils vous permettent de coller du texte, des URL, des données d'image ou d'autres contenus afin de générer un résultat dans votre navigateur.",
              "Évitez d'envoyer des informations privées, sensibles ou confidentielles sauf si vous acceptez qu'elles soient traitées pour la fonction demandée."
            ]
          },
          {
            title: "Récupération de pages et aperçus",
            body: [
              "Certains outils peuvent récupérer des métadonnées publiques de pages web, des images d'aperçu, des miniatures ou d'autres ressources publiques pour afficher un résultat.",
              "Ces requêtes servent à la fonctionnalité choisie et ne doivent être utilisées qu'avec des pages ou contenus que vous êtes autorisé à analyser ou consulter."
            ]
          },
          {
            title: "Données d'usage",
            body: [
              "Des informations techniques de base comme le type de navigateur, les données d'appareil ou des journaux d'usage approximatifs peuvent être collectées pour faire fonctionner le site, prévenir les abus et améliorer la fiabilité.",
              "Des services d'analyse, de publicité ou similaires pourront éventuellement être ajoutés plus tard pour comprendre l'usage du site ou soutenir le projet. Si cela arrive, cette page devra être mise à jour."
            ]
          },
          {
            title: "Services tiers",
            body: [
              "Ce site peut s'appuyer sur des services tiers d'hébergement, d'infrastructure ou d'intégration qui traitent des données techniques limitées dans le cadre de la mise à disposition du site.",
              "Chaque service tiers peut avoir ses propres pratiques et conditions de confidentialité."
            ]
          },
          {
            title: "Vos choix",
            body: [
              "Si vous ne souhaitez pas qu'une certaine information soit traitée, ne l'envoyez pas via les outils.",
              "Si vous ajoutez plus tard une vraie adresse e-mail d'assistance, vous pourrez aussi l'utiliser pour des questions simples liées à la confidentialité."
            ]
          }
        ]
      },
      terms: {
        title: "Conditions d'utilisation",
        description: "Consultez les conditions de base pour utiliser ce petit site indépendant d'outils en ligne.",
        intro: "En utilisant ce site, vous acceptez d'utiliser les outils de manière responsable et uniquement à des fins légales.",
        sections: [
          {
            title: "Usage acceptable",
            body: ["Vous pouvez utiliser le site pour des tâches normales de travail personnel, éducatif ou professionnel."],
            bullets: [
              "N'utilisez pas le site de manière abusive, ne le surchargez pas et n'essayez pas d'interférer avec son fonctionnement normal.",
              "N'utilisez pas les outils pour des activités illégales, nuisibles, contrefaisantes ou abusives.",
              "N'envoyez que des contenus ou URL que vous avez le droit d'utiliser, d'examiner ou de traiter."
            ]
          },
          {
            title: "Votre responsabilité",
            body: [
              "Vous êtes responsable des données que vous saisissez, des URL que vous analysez et de la manière dont vous utilisez les résultats générés par les outils.",
              "Vérifiez les résultats avant de vous y fier pour des décisions de publication, de conformité, de marketing ou techniques."
            ]
          },
          {
            title: "Service fourni en l'état",
            body: [
              "Les outils sont fournis en l'état et selon leur disponibilité.",
              "Les fonctionnalités peuvent changer, être mises à jour, devenir indisponibles ou produire des résultats incomplets sans préavis."
            ]
          },
          {
            title: "Absence de garantie et responsabilité limitée",
            body: [
              "Dans la mesure permise par la loi, ce site ne fournit aucune garantie concernant l'exactitude, la disponibilité ou l'adaptation à un usage particulier.",
              "L'exploitant du site n'est pas responsable des pertes ou dommages résultant de votre utilisation des outils ou de votre confiance dans leurs résultats."
            ]
          }
        ]
      },
      about: {
        title: "À propos",
        description: "Découvrez l'objectif de ce site d'outils multilingue et le public visé.",
        intro:
          "Ce site web est un hub pratique et multilingue d'outils utilitaires basés sur le navigateur, pensés pour être simples d'accès et d'utilisation.",
        sections: [
          {
            title: "Ce que propose le site",
            body: [
              "Le site se concentre sur des outils simples pour les créateurs, marketeurs et développeurs qui veulent des résultats rapides sans installer de logiciel supplémentaire.",
              "On y trouve par exemple des aides pour les images, des outils d'aperçu, des utilitaires de formatage, des outils de liens et de petits accélérateurs pour les tâches web du quotidien."
            ]
          },
          {
            title: "Conçu pour plusieurs langues",
            body: [
              "Le site est pensé pour prendre en charge plusieurs langues afin que les visiteurs puissent consulter les outils et les informations principales dans une langue plus confortable.",
              "L'objectif est de proposer une expérience claire, légère et cohérente d'une langue à l'autre."
            ]
          },
          {
            title: "Simple et rassurant",
            body: [
              "L'intention est d'offrir un site d'outils indépendant, propre, avec des pages pratiques, des textes compréhensibles et une navigation accessible.",
              "Le projet continuera à s'améliorer étape par étape avec un accent sur les fonctions utiles et une expérience facile à maintenir pour les débutants."
            ]
          }
        ]
      }
    },
    contact: {
      title: "Contact",
      description: "Consultez le contact provisoire actuel de ce site d'outils et remplacez-le plus tard par vos vraies coordonnées d'assistance.",
      intro:
        "Si vous souhaitez recevoir des messages des utilisateurs, gardez le moyen de contact simple et facile à maintenir. Vous pourrez remplacer les informations de démonstration avant le lancement.",
      emailLabel: "E-mail de contact",
      emailValue: "hello@example.com",
      emailHelp: "Valeur provisoire uniquement — remplacez-la par votre vraie adresse d'assistance avant le lancement.",
      replaceTitle: "Facile à modifier plus tard",
      replaceBody:
        "Cette page est volontairement simple pour qu'un débutant puisse remplacer rapidement l'e-mail par une vraie adresse, un lien vers un formulaire d'assistance ou un moyen de contact social sans refaire toute la mise en page.",
      responseTitle: "Sujets pour lesquels les utilisateurs peuvent vous contacter",
      responseBody:
        "Les sujets typiques incluent des outils défectueux, des problèmes de traduction, des retours, des questions de partenariat ou des demandes générales d'assistance."
    }
  },
  de: {
    footerLinks: {
      privacy: "Datenschutz",
      terms: "Nutzungsbedingungen",
      about: "Über uns",
      contact: "Kontakt"
    },
    legal: {
      privacy: {
        title: "Datenschutz",
        description: "Erfahren Sie mehr über die grundlegenden Datenschutzpraktiken dieser mehrsprachigen browserbasierten Tools-Website.",
        intro:
          "Diese Website ist ein kleines unabhängiges Tools-Hub. Ziel ist es, den Umgang mit Daten einfach, begrenzt und leicht verständlich zu halten.",
        sections: [
          {
            title: "Informationen, die Sie in Tools eingeben",
            body: [
              "Einige Tools ermöglichen es, Text, URLs, Bilddaten oder andere Inhalte einzufügen, damit im Browser ein Ergebnis erzeugt werden kann.",
              "Bitte senden Sie keine privaten, sensiblen oder vertraulichen Inhalte, es sei denn, Sie sind damit einverstanden, dass diese Daten für die gewünschte Tool-Funktion verarbeitet werden."
            ]
          },
          {
            title: "Abruf von Webseiten und Vorschauen",
            body: [
              "Einige Tools können öffentliche Webseiten-Metadaten, Vorschaubilder, Thumbnails oder andere öffentlich verfügbare Ressourcen abrufen, um ein Ergebnis anzuzeigen.",
              "Diese Abrufe dienen der von Ihnen gewählten Funktion und sollten nur für Seiten oder Inhalte verwendet werden, die Sie analysieren oder referenzieren dürfen."
            ]
          },
          {
            title: "Nutzungsdaten",
            body: [
              "Grundlegende technische Informationen wie Browsertyp, Geräteinformationen oder ungefähre Nutzungsprotokolle können erhoben werden, um die Website zu betreiben, Missbrauch zu verhindern und die Zuverlässigkeit zu verbessern.",
              "Künftig könnten Analyse-, Werbe- oder ähnliche Dienste ergänzt werden, um die Nutzung der Website besser zu verstehen oder das Projekt zu unterstützen. Wenn das passiert, sollte diese Seite aktualisiert werden."
            ]
          },
          {
            title: "Dienste von Drittanbietern",
            body: [
              "Diese Website kann Hosting-, Infrastruktur- oder eingebettete Drittanbieter-Dienste nutzen, die im Rahmen der Bereitstellung der Website begrenzte technische Daten verarbeiten.",
              "Jeder Drittanbieter-Dienst kann eigene Datenschutzbedingungen und -praktiken haben."
            ]
          },
          {
            title: "Ihre Wahlmöglichkeiten",
            body: [
              "Wenn Sie nicht möchten, dass bestimmte Informationen verarbeitet werden, geben Sie diese nicht in die Tools ein.",
              "Wenn Sie später eine echte Support-E-Mail ergänzen, können Sie diesen Kanal auch für einfache datenschutzbezogene Anfragen nutzen."
            ]
          }
        ]
      },
      terms: {
        title: "Nutzungsbedingungen",
        description: "Lesen Sie die grundlegenden Bedingungen für die Nutzung dieser kleinen unabhängigen Online-Tools-Website.",
        intro: "Durch die Nutzung dieser Website erklären Sie sich damit einverstanden, die Tools verantwortungsvoll und nur für rechtmäßige Zwecke zu verwenden.",
        sections: [
          {
            title: "Zulässige Nutzung",
            body: ["Sie dürfen die Website für normale persönliche, schulische oder geschäftliche Arbeitsabläufe verwenden."],
            bullets: [
              "Missbrauchen Sie die Website nicht, überlasten Sie sie nicht und versuchen Sie nicht, den normalen Betrieb zu stören.",
              "Verwenden Sie die Tools nicht für rechtswidrige, schädliche, rechtsverletzende oder missbräuchliche Aktivitäten.",
              "Senden Sie nur Inhalte oder URLs, die Sie verwenden, prüfen oder verarbeiten dürfen."
            ]
          },
          {
            title: "Ihre Verantwortung",
            body: [
              "Sie sind für die von Ihnen eingegebenen Daten, die analysierten URLs und die Nutzung der von den Tools erzeugten Ergebnisse verantwortlich.",
              "Bitte prüfen Sie die Ergebnisse, bevor Sie sich bei Veröffentlichungs-, Compliance-, Marketing- oder technischen Entscheidungen darauf verlassen."
            ]
          },
          {
            title: "Bereitstellung wie gesehen",
            body: [
              "Die Tools werden ohne Zusicherung und nach Verfügbarkeit bereitgestellt.",
              "Funktionen können sich ohne Vorankündigung ändern, aktualisiert werden, entfallen oder unvollständige Ergebnisse liefern."
            ]
          },
          {
            title: "Keine Gewährleistung und beschränkte Haftung",
            body: [
              "Soweit gesetzlich zulässig, übernimmt diese Website keine Gewähr für Genauigkeit, Verfügbarkeit oder Eignung für einen bestimmten Zweck.",
              "Der Betreiber haftet nicht für Verluste oder Schäden, die aus der Nutzung der Tools oder dem Vertrauen auf Tool-Ergebnisse entstehen."
            ]
          }
        ]
      },
      about: {
        title: "Über uns",
        description: "Erfahren Sie, wofür diese mehrsprachige Tools-Website gedacht ist und wen sie unterstützen soll.",
        intro:
          "Diese Website ist ein praktisches mehrsprachiges Hub für browserbasierte Hilfstools, die leicht zugänglich und einfach zu verwenden sind.",
        sections: [
          {
            title: "Was die Website bietet",
            body: [
              "Im Mittelpunkt stehen unkomplizierte Tools für Creator, Marketer und Entwickler, die schnelle Ergebnisse ohne zusätzliche Software möchten.",
              "Dazu gehören Bildhilfen, Vorschau-Tools, Formatierungswerkzeuge, Link-Tools und kleine Helfer für alltägliche Web-Aufgaben."
            ]
          },
          {
            title: "Mehrsprachig gedacht",
            body: [
              "Die Website unterstützt mehrere Sprachen, damit Besucher Tools und grundlegende Informationen in einer vertrauteren Sprache nutzen können.",
              "Ziel ist eine klare, leichte und konsistente Erfahrung über alle Sprachen hinweg."
            ]
          },
          {
            title: "Einfach und vertrauenswürdig",
            body: [
              "Gedacht ist die Website als saubere unabhängige Tools-Seite mit praktischen Inhalten, verständlichen Texten und zugänglicher Navigation.",
              "Das Projekt wird Schritt für Schritt weiter verbessert, mit Fokus auf nützliche Funktionen und eine anfängerfreundliche Pflege."
            ]
          }
        ]
      }
    },
    contact: {
      title: "Kontakt",
      description: "Hier finden Sie den aktuellen Kontakt-Platzhalter dieser Tools-Website, den Sie später durch echte Support-Daten ersetzen können.",
      intro:
        "Wenn Sie Rückmeldungen von Nutzern erhalten möchten, sollte die Kontaktmöglichkeit einfach und pflegeleicht bleiben. Die Platzhalterangaben unten können Sie vor dem Start austauschen.",
      emailLabel: "Kontakt-E-Mail",
      emailValue: "hello@example.com",
      emailHelp: "Nur ein Platzhalter — bitte vor dem Launch durch Ihre echte Support-E-Mail ersetzen.",
      replaceTitle: "Später leicht austauschbar",
      replaceBody:
        "Diese Seite ist bewusst einfach gehalten, damit Einsteiger später schnell eine echte E-Mail-Adresse, einen Link zu einem Support-Formular oder einen Social-Kontakt einfügen können, ohne das Layout neu zu bauen.",
      responseTitle: "Wozu Nutzer Sie kontaktieren können",
      responseBody:
        "Typische Themen sind defekte Tools, Übersetzungsprobleme, Feedback, Partnerschaftsanfragen oder allgemeine Support-Fragen."
    }
  }
};
